#undef ADVANCED_DEFAUT_OPENWEATHER_API_KEY
#undef INFLUXDB_DEFAULT_SERVER_URL
#undef INFLUXDB_DEFAULT_ORG
#undef INFLUXDB_DEFAULT_BUCKET
#undef INFLUXDB_DEFAULT_TOKEN 

#define ADVANCED_DEFAUT_OPENWEATHER_API_KEY "7f5b476a66638c1f04519bb35c43d0b3"
#define INFLUXDB_DEFAULT_SERVER_URL F("https://us-east-1-1.aws.cloud2.influxdata.com")
#define INFLUXDB_DEFAULT_TOKEN F("9WN9Eybnt0gFO6rbU_IHTCBYX-5S2cTWL6qZSqreDMAiQQ5jevU2zTB1o0p_uSuvsWj0nJ_Ic4NFFm6puiIkPw==")
#define INFLUXDB_DEFAULT_ORG F("demos@bonitoo4influxdata.com")
#define INFLUXDB_DEFAULT_BUCKET F("iot_center")

